/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        // GroupsScreen.jsx (Tailwind refactor) shipped using an invented, one-off
        // color vocabulary instead of the semantic tokens every other screen uses
        // (surface-container/on-surface/primary/etc. above) - none of these names
        // existed in this file, so every class using them rendered with no color
        // at all. Aliased to the real, already-established values rather than
        // rewriting the 77 call sites across that file.
        "collegiate-dark": "#030a14",
        "collegiate-blue": "#0e182a",
        "antique-gold": "#b89c5b",
        "antique-dark": "#030a14",
        "gold-hover": "#d1b87a",
        "card-border": "#2a313d",
        "card-surface": "#0a1120",
        "text-headline": "#ffffff",
        "text-muted": "#bcc1ca",
        "slate-accent": "#34d399",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary": "#030a14",
        "primary": "#b89c5b",
        "primary-hover": "#d1b87a",
        "surface-container-highest": "#172338",
        "background": "#030a14",
        "outline-variant": "#2a313d",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#e8d8b5",
        "surface-dim": "#030a14",
        "tertiary-container": "#1e3a5f",
        "on-primary-fixed": "#2a1700",
        "on-surface-variant": "#bcc1ca",
        "primary-fixed-dim": "#d1b87a",
        "secondary": "#34d399",
        "on-primary": "#030a14",
        "on-background": "#ffffff",
        "outline": "#2a313d",
        "secondary-fixed": "#34d399",
        "surface-container-lowest": "#030a14",
        "secondary-container": "rgba(52, 211, 153, 0.15)",
        "surface-container-low": "#061c41",
        "surface-variant": "#0e182a",
        "on-surface": "#ffffff",
        "on-primary-container": "#030a14",
        "inverse-on-surface": "#030a14",
        "on-tertiary-fixed": "#ffffff",
        "surface": "#030a14",
        "on-tertiary-fixed-variant": "#b89c5b",
        "on-secondary-container": "#34d399",
        "surface-tint": "#b89c5b",
        "error-container": "rgba(248, 113, 113, 0.12)",
        "on-tertiary-container": "#ffffff",
        "on-primary-fixed-variant": "#030a14",
        "on-secondary": "#030a14",
        "inverse-surface": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#15243d",
        "tertiary": "#8bb5e8",
        "surface-container": "#0a1120",
        "surface-container-high": "#0e182a",
        "secondary-fixed-dim": "#34d399",
        "on-error-container": "#f87171",
        "primary-container": "#b89c5b",
        "tertiary-fixed": "#b89c5b",
        "error": "#f87171",
        "inverse-primary": "#d1b87a",
        "dim": "#7a8291"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "0.75rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "margin": "1.5rem",
        "gutter": "1.25rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem"
      },
      "fontFamily": {
        "label-lg": [ "Inter", "sans-serif" ],
        "headline-xl-mobile": [ "Oswald", "sans-serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "headline-xl": [ "Oswald", "sans-serif" ],
        "label-sm": [ "Inter", "sans-serif" ],
        "label-md": [ "Inter", "sans-serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "headline-lg": [ "Oswald", "sans-serif" ],
        "display": [ "Oswald", "sans-serif" ],
        "body-md": [ "Inter", "sans-serif" ],
        "metric-val": [ "Oswald", "sans-serif" ],
        "headline-md": [ "Oswald", "sans-serif" ]
      },
      "fontSize": {
        "label-lg": [ "13px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "600" } ],
        "headline-xl-mobile": [ "28px", { "lineHeight": "32px", "letterSpacing": "0.02em", "fontWeight": "700" } ],
        "body-sm": [ "12px", { "lineHeight": "16px", "fontWeight": "400" } ],
        "headline-xl": [ "36px", { "lineHeight": "40px", "letterSpacing": "0.02em", "fontWeight": "700" } ],
        "label-sm": [ "10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" } ],
        "label-md": [ "11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "700" } ],
        "body-lg": [ "16px", { "lineHeight": "24px", "fontWeight": "400" } ],
        "headline-lg": [ "24px", { "lineHeight": "28px", "letterSpacing": "0.03em", "fontWeight": "600" } ],
        "display": [ "48px", { "lineHeight": "52px", "letterSpacing": "0.02em", "fontWeight": "700" } ],
        "body-md": [ "14px", { "lineHeight": "20px", "fontWeight": "400" } ],
        "metric-val": [ "28px", { "lineHeight": "30px", "letterSpacing": "0.01em", "fontWeight": "700" } ],
        "headline-md": [ "18px", { "lineHeight": "24px", "letterSpacing": "0.04em", "fontWeight": "600" } ]
      }
    }
  },
  plugins: [],
}
